### ISSUE TITLE
Hírbejegyzés szerkesztő

### ISSUE THREAD

**Issue by jaraymatyas** [SzE-ProjektmunKATEam/egeszsegugyi-rendelo#24]
Mint egészségügyi dolgozó szeretném szerkeszteni az oldal hírlapját, hogy mindig az aktuális adatokat jelenítse meg.

**Előfeltétel:**
Miután megnyitjuk az oldalt és bejelentkezünk, mint egészségügyi dolgozó.

**Feladat felbontása:**

- [x] #8 
- [x] back-end a szerkesztőlap elemeihez (’wysiwyg editor’)
- [x] front-end a szövegszerkesztőhöz

**Elfogadási feltételek:**

- mint egészségügyi dolgozó,
- megnyomom a szerkesztés gombot,
- megjelennek a szerkesztői felület,
- szerkeszteni tudom a szövegeket,
- mentés gombbal elmentem a változtatásokat.

_Originally posted by @vdelia25 in https://github.com/SzE-ProjektmunKATEam/egeszsegugyi-rendelo/issues/24#issuecomment-1323886858_

**Comment by vdelia25** [comment]
**Előfeltétel:**
Miután megnyitjuk az oldalt és bejelentkezünk, mint egészségügyi dolgozó, megjelenik a Hírlap szerkesztése lehetőség.

**Feladat felbontása:**

- [ ] Adatbázis létrehozása-Adatbázis létrehozása
- [ ] back-end a szerkesztőlap elemeihez (’wysiwyg editor’)
- [ ] front-end a szövegszerkesztőhöz


**Elfogadási feltételek:**

- [ ] mint dolgozóként regisztrált, szerkeszteni tudom a felületet
- [ ] megjelennek a ’wysiwyg editor’ elemei
- [ ] szerkeszteni tudom a szövegeket, és az oldal alján a mentés gombbal láthatóak lesznek a változtatások
